// SPDX-FileCopyrightText: 2026 Naraen Rammoorthi <naraen13@gmail.com>
// SPDX-License-Identifier: Apache-2.0

import { useEffect, useMemo, useState } from "react";
import { Link, useParams } from "@tanstack/react-router";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import { ArrowLeft, Check, ChevronDown, CircleAlert, GitCommitHorizontal, GitPullRequest, MessageSquare, Plus, X } from "lucide-react";
import { toast } from "sonner";
import { auth, prReviews } from "@/lib/api";
import type { ReviewFile, ReviewThread, ReviewVerdict } from "@/lib/types";
import { useAuthGuard } from "@/hooks/use-auth";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Skeleton } from "@/components/ui/skeleton";

const activeStates = new Set(["open", "changes_requested", "approved"]);
const markdownClass = "prose prose-sm dark:prose-invert max-w-none break-words prose-a:text-primary";

function Markdown({ body }: { body: string }) {
  return <div className={markdownClass}><ReactMarkdown remarkPlugins={[remarkGfm]}>{body}</ReactMarkdown></div>;
}

function Composer({ onSubmit, busy, label = "Comment", initial = "" }: { onSubmit: (body: string) => void; busy: boolean; label?: string; initial?: string }) {
  const [body, setBody] = useState(initial);
  const [preview, setPreview] = useState(false);
  return <div className="overflow-hidden rounded-lg border border-border bg-card">
    <div className="flex border-b border-border bg-muted/50 text-xs"><button type="button" onClick={() => setPreview(false)} aria-pressed={!preview} className={`px-4 py-2 ${!preview ? "font-semibold text-foreground" : "text-muted-foreground"}`}>Write</button><button type="button" onClick={() => setPreview(true)} aria-pressed={preview} className={`px-4 py-2 ${preview ? "font-semibold text-foreground" : "text-muted-foreground"}`}>Preview</button></div>
    <div className="p-3">{preview ? <div className="min-h-24 rounded-md p-2">{body.trim() ? <Markdown body={body} /> : <span className="text-sm text-muted-foreground">Nothing to preview yet.</span>}</div> : <Textarea aria-label={label} value={body} onChange={e => setBody(e.target.value)} onKeyDown={e => { if (e.key === "Enter" && (e.metaKey || e.ctrlKey) && body.trim()) { e.preventDefault(); onSubmit(body.trim()); setBody(""); } }} rows={4} placeholder="Leave a comment… Markdown is supported" />}
      <div className="mt-3 flex justify-end"><Button size="sm" disabled={busy || !body.trim()} onClick={() => { onSubmit(body.trim()); setBody(""); }}>{label}</Button></div>
    </div>
  </div>;
}

function ThreadCard({ thread, onReply, onResolve, busy }: { thread: ReviewThread; onReply: (id: string, body: string) => void; onResolve: (id: string, resolved: boolean) => void; busy: boolean }) {
  return <section id={`thread-${thread.id}`} aria-label={`Conversation on ${thread.path ?? "review"}`} className="my-3 overflow-hidden rounded-lg border border-border bg-card">
    <div className="flex flex-wrap items-center justify-between gap-2 border-b border-border bg-muted/50 px-3 py-2 text-xs"><span className="font-medium">{thread.path ? `${thread.path} · line ${thread.start_line}${thread.end_line && thread.end_line !== thread.start_line ? `–${thread.end_line}` : ""}` : "General conversation"}{thread.outdated ? " · Outdated" : ""}</span><Button variant="ghost" size="sm" disabled={busy} onClick={() => onResolve(thread.id, !thread.resolved_at)}>{thread.resolved_at ? "Reopen" : "Resolve conversation"}</Button></div>
    {thread.comments.map(comment => <div key={comment.id} className="border-b border-border px-3 py-3 text-sm"><p className="mb-2 text-xs text-muted-foreground">{new Date(comment.created_at).toLocaleString()}{comment.pending ? " · Pending" : ""}</p><Markdown body={comment.body} />{comment.suggestion && <div className="mt-3 rounded-md border border-success/30 bg-success/10 p-3 text-xs"><span className="font-semibold">Suggestion · apply manually</span><pre className="mt-2 overflow-auto font-mono">{comment.suggestion}</pre></div>}</div>)}
    <div className="p-3"><Composer label="Reply" busy={busy} onSubmit={body => onReply(thread.id, body)} /></div>
  </section>;
}

function DiffFile({ file, threads, onComment, onReply, onResolve, busy, revision, number }: { file: ReviewFile; threads: ReviewThread[]; onComment: (path: string, line: number, body: string, draft: boolean) => void; onReply: (id: string, body: string) => void; onResolve: (id: string, resolved: boolean) => void; busy: boolean; revision: number; number: string }) {
  const key = `observal-review-viewed-${number}-${revision}-${file.path}`;
  const [viewed, setViewed] = useState(() => localStorage.getItem(key) === "1");
  const [line, setLine] = useState<number | null>(null);
  const [draft, setDraft] = useState(false);
  const [body, setBody] = useState("");
  const [expanded, setExpanded] = useState(false);
  return <section id={`file-${encodeURIComponent(file.path)}`} className="mb-4 overflow-hidden rounded-lg border border-border bg-card">
    <div className="flex flex-wrap items-center gap-2 bg-muted/50 px-3 py-2 text-xs"><span className="font-mono font-semibold">{file.path}</span><span className="capitalize text-muted-foreground">{file.status}</span><span className="ml-auto text-success">+{file.additions ?? "?"}</span><span className="text-destructive">−{file.deletions ?? "?"}</span><label className="ml-2 flex items-center gap-1"><input type="checkbox" checked={viewed} onChange={e => { setViewed(e.target.checked); if (e.target.checked) localStorage.setItem(key, "1"); else localStorage.removeItem(key); }} /> Viewed</label></div>
    {file.too_large ? <div className="p-4 text-sm text-muted-foreground">Large file. <button className="underline" type="button" onClick={() => setExpanded(true)}>Load anyway</button>{expanded && <p>Reload the comparison with the full-file option above.</p>}</div> : viewed ? <div className="p-3 text-xs text-muted-foreground">Marked as viewed. Uncheck to show this file.</div> : <div className="overflow-x-auto"><table className="w-full border-collapse font-mono text-xs" aria-label={`Diff for ${file.path}`}><tbody>{file.hunks?.map((hunk, index) => <FragmentHunk key={index} hunk={hunk} file={file} line={line} setLine={setLine} threads={threads} draft={draft} setDraft={setDraft} body={body} setBody={setBody} onComment={onComment} onReply={onReply} onResolve={onResolve} busy={busy} />)}</tbody></table></div>}
  </section>;
}

function FragmentHunk({ hunk, file, line, setLine, threads, draft, setDraft, body, setBody, onComment, onReply, onResolve, busy }: { hunk: NonNullable<ReviewFile["hunks"]>[number]; file: ReviewFile; line: number | null; setLine: (line: number | null) => void; threads: ReviewThread[]; draft: boolean; setDraft: (value: boolean) => void; body: string; setBody: (value: string) => void; onComment: (path: string, line: number, body: string, draft: boolean) => void; onReply: (id: string, body: string) => void; onResolve: (id: string, resolved: boolean) => void; busy: boolean }) {
  return <><tr><td colSpan={4} className="bg-info/10 px-3 py-1 text-info">@@ −{hunk.base_start},{hunk.base_lines} +{hunk.head_start},{hunk.head_lines} @@</td></tr>{hunk.lines.map((entry, index) => <tr key={`${index}-${entry.b}-${entry.h}`} className={`group ${entry.t === "add" ? "bg-success/10" : entry.t === "del" ? "bg-destructive/10" : ""}`} aria-label={`line ${entry.h ?? entry.b}, ${entry.t}`}><td className="w-10 select-none border-r border-border px-2 text-right text-muted-foreground">{entry.b}</td><td className="w-10 select-none border-r border-border px-2 text-right text-muted-foreground">{entry.h}</td><td className="w-7 text-center">{entry.h && <button aria-label={`Comment on ${file.path} line ${entry.h}`} type="button" className="rounded opacity-0 hover:bg-primary hover:text-primary-foreground focus-visible:opacity-100 group-hover:opacity-100" onClick={() => setLine(entry.h!)}><Plus className="size-3.5" /></button>}</td><td className="whitespace-pre px-2">{entry.t === "add" ? "+" : entry.t === "del" ? "−" : " "}{entry.s}</td></tr>)}
    {line !== null && hunk.lines.some(entry => entry.h === line) && <tr><td colSpan={4} className="p-3 font-sans"><div className="max-w-2xl space-y-2"><label className="flex items-center gap-2 text-xs"><input type="checkbox" checked={draft} onChange={e => setDraft(e.target.checked)} /> Add to pending review</label><Textarea aria-label={`Comment on ${file.path} line ${line}`} value={body} onChange={e => setBody(e.target.value)} placeholder="Comment on this line…" rows={3} /><div className="flex gap-2"><Button size="sm" disabled={!body.trim() || busy} onClick={() => { onComment(file.path, line, body.trim(), draft); setBody(""); setLine(null); }}>{draft ? "Start a review" : "Add single comment"}</Button><Button size="sm" variant="ghost" onClick={() => setLine(null)}>Cancel</Button></div></div></td></tr>}
    {threads.filter(thread => thread.path === file.path && hunk.lines.some(entry => entry.h === thread.start_line)).map(thread => <tr key={thread.id}><td colSpan={4} className="p-3 font-sans"><ThreadCard thread={thread} onReply={onReply} onResolve={onResolve} busy={busy} /></td></tr>)}
  </>;
}

export default function ReviewDetailPage() {
  useAuthGuard();
  const { number } = useParams({ from: "/_authed/review_/$number" });
  const qc = useQueryClient();
  const [tab, setTab] = useState<"conversation" | "files" | "revisions" | "checks">("conversation");
  const [from, setFrom] = useState("base");
  const [to, setTo] = useState("head");
  const [full, setFull] = useState(false);
  const [summary, setSummary] = useState("");
  const [verdict, setVerdict] = useState<ReviewVerdict>("comment");
  const [showSubmit, setShowSubmit] = useState(false);
  const [category, setCategory] = useState("");
  const [override, setOverride] = useState("");
  const [reason, setReason] = useState("");
  const [requestedId, setRequestedId] = useState("");
  const { data: me } = useQuery({ queryKey: ["auth", "whoami"], queryFn: auth.whoami });
  const { data: review, isPending, isError, refetch } = useQuery({ queryKey: ["pr-review", number], queryFn: () => prReviews.detail(number) });
  const { data: gate } = useQuery({ queryKey: ["pr-review", number, "gate"], queryFn: () => prReviews.gate(number), enabled: !!review });
  const { data: timeline } = useQuery({ queryKey: ["pr-review", number, "timeline"], queryFn: () => prReviews.timeline(number), enabled: !!review && tab === "conversation" });
  const { data: threads } = useQuery({ queryKey: ["pr-review", number, "threads"], queryFn: () => prReviews.threads(number), enabled: !!review && (tab === "conversation" || tab === "files") });
  const { data: files } = useQuery({ queryKey: ["pr-review", number, "files", from, to, full], queryFn: () => prReviews.diff(number, { from, to, ...(full ? { full: "true" } : {}) }), enabled: !!review && tab === "files" });
  const { data: checks } = useQuery({ queryKey: ["pr-review", number, "checks"], queryFn: () => prReviews.checks(number), enabled: !!review && tab === "checks" });
  const action = useMutation({ mutationFn: (run: () => Promise<unknown>) => run(), onSuccess: async () => { await qc.invalidateQueries({ queryKey: ["pr-review", number] }); await qc.invalidateQueries({ queryKey: ["pr-reviews"] }); toast.success("Review updated"); }, onError: (err: Error) => toast.error(err.message) });
  useEffect(() => {
    if (!review?.id) return;
    let closed = false;
    let unsubscribe: (() => void) | undefined;
    import("@/lib/graphql-ws").then(({ subscribeToReviewId }) => {
      if (!closed) unsubscribe = subscribeToReviewId(review.id, () => {
        qc.invalidateQueries({ queryKey: ["pr-review", number] });
        qc.invalidateQueries({ queryKey: ["pr-reviews"] });
      });
    });
    return () => { closed = true; unsubscribe?.(); };
  }, [review?.id, number, qc]);
  const isAuthor = !!review && me?.id === review.author_id;
  const isOpen = !!review && activeStates.has(review.state);
  const unresolved = useMemo(() => (threads ?? []).filter(thread => !thread.resolved_at), [threads]);
  useEffect(() => { const onKey = (event: KeyboardEvent) => { if (event.key === "r" && !(event.target instanceof HTMLInputElement || event.target instanceof HTMLTextAreaElement)) setShowSubmit(true); }; window.addEventListener("keydown", onKey); return () => window.removeEventListener("keydown", onKey); }, []);
  if (isPending) return <div className="mx-auto max-w-7xl space-y-4 p-6"><Skeleton className="h-12 w-1/2" /><Skeleton className="h-9" /><Skeleton className="h-96" /></div>;
  if (isError || !review) return <div className="mx-auto max-w-7xl p-8 text-sm"><h1 className="text-xl font-semibold">Review unavailable</h1><p className="my-3 text-muted-foreground">This review may be private or no longer available.</p><Button variant="outline" onClick={() => refetch()}>Try again</Button></div>;
  return <div className="mx-auto max-w-7xl space-y-5 px-4 py-6 sm:px-6">
    <header><Link to="/review" className="inline-flex items-center gap-1 text-xs text-muted-foreground hover:text-foreground"><ArrowLeft className="size-3.5" /> Review queue</Link><div className="mt-3 flex flex-wrap items-center gap-2"><h1 className="text-2xl font-semibold tracking-tight">{review.title}</h1><span className="font-mono text-xl text-muted-foreground">#{review.number}</span></div><p className="mt-2 flex flex-wrap items-center gap-2 text-sm text-muted-foreground"><span className="rounded-full bg-info/10 px-2 py-0.5 font-medium capitalize text-info">{review.state.replaceAll("_", " ")}</span>Revision {review.head_revision} · {review.subject_type} · v{review.version}</p>{isAuthor && isOpen && (review.subject_type === "agent" ? <Link to="/agents/builder" search={{ edit: review.subject_id }} className="mt-3 inline-flex rounded-md border border-border px-3 py-1.5 text-sm font-medium hover:bg-muted">Edit version</Link> : <Link to="/components/$componentId" params={{ componentId: review.subject_id }} search={{ type: `${review.subject_type}s` as "mcps" | "skills" | "hooks" | "prompts" | "sandboxes" }} className="mt-3 inline-flex rounded-md border border-border px-3 py-1.5 text-sm font-medium hover:bg-muted">Edit version</Link>)}</header>
    <div className="flex flex-wrap items-center justify-between gap-3 border-b border-border"><nav aria-label="Review sections" className="flex gap-1 overflow-auto">{(["conversation", "files", "revisions", "checks"] as const).map(name => <button key={name} type="button" onClick={() => setTab(name)} aria-current={tab === name ? "page" : undefined} className={`whitespace-nowrap border-b-2 px-3 py-2 text-sm capitalize ${tab === name ? "border-foreground font-semibold" : "border-transparent text-muted-foreground"}`}>{name === "files" ? "Files changed" : name}</button>)}</nav>{isOpen && <Button size="sm" variant="outline" onClick={() => setShowSubmit(value => !value)}>Review changes <ChevronDown className="ml-1 size-4" /></Button>}</div>
    {showSubmit && isOpen && <section className="rounded-xl border border-border bg-card p-4"><h2 className="mb-3 text-sm font-semibold">Submit review</h2><Textarea aria-label="Review summary" value={summary} onChange={e => setSummary(e.target.value)} placeholder="Leave a summary…" /><div className="my-3 space-y-2 text-sm">{(["comment", "approve", "request_changes"] as const).map(choice => <label key={choice} className="flex items-center gap-2"><input type="radio" name="verdict" checked={verdict === choice} onChange={() => setVerdict(choice)} disabled={isAuthor && (choice === "request_changes" || (choice === "approve" && !review.self_approval_allowed))} />{choice === "request_changes" ? "Request changes" : choice === "approve" ? "Approve" : "Comment"}</label>)}</div><Button size="sm" disabled={action.isPending || (verdict === "request_changes" && !summary.trim())} onClick={() => action.mutate(() => prReviews.submit(number, verdict, summary), { onSuccess: () => { setShowSubmit(false); setSummary(""); } })}>Submit review</Button></section>}
    <div className="grid items-start gap-6 lg:grid-cols-[minmax(0,1fr)_270px]"><main className="min-w-0 space-y-4">
      {tab === "conversation" && <><section className="rounded-xl border border-border bg-card p-5"><div className="mb-3 flex items-center gap-2 text-xs text-muted-foreground"><GitPullRequest className="size-4" /> Opened {new Date(review.opened_at).toLocaleDateString()}</div><Markdown body={review.body || "No description provided."} /></section><div className="space-y-3 border-l border-border pl-5">{timeline?.items.map(event => <div key={event.id} className="relative text-sm before:absolute before:-left-[26px] before:top-2 before:size-2 before:rounded-full before:bg-border"><span className="font-medium capitalize">{event.kind.replaceAll("_", " ")}</span><span className="ml-2 text-xs text-muted-foreground">{new Date(event.created_at).toLocaleString()}</span>{event.body && <div className="mt-2 rounded-lg border border-border bg-card p-3"><Markdown body={event.body} /></div>}</div>)}</div>{(threads ?? []).filter(thread => !thread.path).map(thread => <ThreadCard key={thread.id} thread={thread} busy={action.isPending} onReply={(id, body) => action.mutate(() => prReviews.reply(number, id, body))} onResolve={(id, value) => action.mutate(() => prReviews.resolve(number, id, value))} />)}{isOpen && <Composer busy={action.isPending} onSubmit={body => action.mutate(() => prReviews.comment(number, body))} />}</>}
      {tab === "files" && <><div className="flex flex-wrap items-center gap-2 rounded-lg border border-border bg-card p-3 text-xs"><label>From <select className="ml-1 rounded border border-border bg-background p-1" value={from} onChange={e => setFrom(e.target.value)}><option value="base">Base</option>{review.revisions.map(rev => <option key={rev.id} value={`r${rev.number}`}>Revision {rev.number}</option>)}</select></label><label>To <select className="ml-1 rounded border border-border bg-background p-1" value={to} onChange={e => setTo(e.target.value)}><option value="head">Head</option>{review.revisions.map(rev => <option key={rev.id} value={`r${rev.number}`}>Revision {rev.number}</option>)}</select></label><label className="ml-auto flex items-center gap-1"><input type="checkbox" checked={full} onChange={e => setFull(e.target.checked)} /> Full context</label><span>{unresolved.length} open conversations</span></div>{files?.filter(file => file.status !== "unchanged").map(file => <DiffFile key={file.path} number={number} revision={review.head_revision} file={file} threads={threads ?? []} busy={action.isPending} onComment={(path, line, body, draft) => action.mutate(() => prReviews.comment(number, body, path, line, draft))} onReply={(id, body) => action.mutate(() => prReviews.reply(number, id, body))} onResolve={(id, resolved) => action.mutate(() => prReviews.resolve(number, id, resolved))} />)}{files?.every(file => file.status === "unchanged") && <p className="text-sm text-muted-foreground">No changes between these revisions.</p>}</>}
      {tab === "revisions" && <div className="overflow-hidden rounded-xl border border-border bg-card">{[...review.revisions].reverse().map(rev => <div key={rev.id} className="flex flex-wrap items-center gap-3 border-b border-border p-4 text-sm"><GitCommitHorizontal className="size-4 text-muted-foreground" /><span className="font-medium">Revision {rev.number}</span><span className="text-muted-foreground">{rev.message || "Changes submitted"} · {new Date(rev.created_at).toLocaleString()}</span><Button variant="ghost" size="sm" className="ml-auto" disabled={rev.pruned} onClick={() => { setFrom(rev.number === 1 ? "base" : `r${rev.number - 1}`); setTo(`r${rev.number}`); setTab("files"); }}>Compare with previous</Button></div>)}</div>}
      {tab === "checks" && <div className="overflow-hidden rounded-xl border border-border bg-card">{checks?.map(check => <div key={check.id} className="flex items-center gap-3 border-b border-border p-4 text-sm">{check.status === "pass" ? <Check className="size-4 text-success" /> : check.status === "fail" ? <X className="size-4 text-destructive" /> : <CircleAlert className="size-4 text-warning" />}<span className="font-medium">{check.name}</span><span className="ml-auto text-xs text-muted-foreground">{check.required ? "Required" : "Advisory"} · {check.status}</span></div>)}{!checks?.length && <p className="p-5 text-sm text-muted-foreground">No checks recorded.</p>}</div>}
      <section className={`overflow-hidden rounded-xl border bg-card ${gate?.ready ? "border-success/50" : "border-border"}`}><h2 className="border-b border-border bg-muted/30 px-4 py-3 text-sm font-semibold">Publication gate</h2><div className="space-y-3 p-4 text-sm"><p className="flex items-center gap-2">{gate?.ready ? <Check className="size-4 text-success" /> : <CircleAlert className="size-4 text-warning" />}{gate?.approvals ?? review.gate.approvals} of {gate?.required ?? review.gate.required} approvals · {gate?.policy_source ?? review.gate.policy_source} policy</p>{(gate?.requirements ?? review.gate.requirements).map((item, index) => <p key={index} className="text-muted-foreground">{item}</p>)}<p className="text-xs text-muted-foreground">{review.threads.unresolved} unresolved conversations</p><div className="flex flex-wrap items-center gap-2 border-t border-border pt-3">{isAuthor && !review.self_approval_allowed ? <><span className="text-xs text-muted-foreground">A reviewer will publish when the gate is ready.</span>{isOpen && <Button variant="outline" size="sm" disabled={action.isPending} onClick={() => { if (window.confirm("Withdraw this review?")) action.mutate(() => prReviews.withdraw(number)); }}>Withdraw</Button>}</> : isOpen && <><Button size="sm" disabled={!gate?.ready || action.isPending} onClick={() => { if (window.confirm(`Publish v${review.version}?`)) action.mutate(() => prReviews.publish(number, category || undefined)); }}>Publish v{review.version}</Button>{review.subject_type === "agent" && <Input className="h-8 w-40" value={category} onChange={e => setCategory(e.target.value)} placeholder="Agent category" aria-label="Agent category" />}{me?.role === "super_admin" && <div className="flex items-center gap-2"><Input className="h-8 w-52" value={override} onChange={e => setOverride(e.target.value)} placeholder="Override reason" aria-label="Override reason" /><Button variant="outline" size="sm" disabled={!override.trim() || action.isPending} onClick={() => { if (window.confirm("Publish without required approvals? This action is audited.")) action.mutate(() => prReviews.publish(number, category || undefined, override)); }}>Publish with override</Button></div>}{!isAuthor && <><Input className="h-8 w-48" value={reason} onChange={e => setReason(e.target.value)} placeholder="Close reason" aria-label="Close reason" /><Button variant="ghost" size="sm" disabled={!reason.trim() || action.isPending} onClick={() => action.mutate(() => prReviews.close(number, reason))}>Close review</Button></>}{isAuthor && <Button variant="outline" size="sm" disabled={action.isPending} onClick={() => { if (window.confirm("Withdraw this review?")) action.mutate(() => prReviews.withdraw(number)); }}>Withdraw</Button>}</>}</div></div></section>
    </main><aside className="space-y-4 rounded-xl border border-border bg-card p-4 text-sm lg:sticky lg:top-6"><h2 className="font-semibold">Reviewers</h2>{review.requested_reviewers.length ? review.requested_reviewers.map(id => <p key={id} className="font-mono text-xs text-muted-foreground">{id}</p>) : <p className="text-xs text-muted-foreground">No reviewers requested individually.</p>}{isOpen && <div className="mt-3 flex flex-wrap gap-2"><Input aria-label="Reviewer user ID" placeholder="Reviewer user ID" value={requestedId} onChange={e => setRequestedId(e.target.value)} className="h-8 min-w-32 flex-1" /><Button size="sm" variant="outline" disabled={!requestedId.trim() || action.isPending} onClick={() => action.mutate(() => prReviews.requestReviewer(number, requestedId.trim()), { onSuccess: () => setRequestedId("") })}>Request reviewer</Button></div>}<div className="border-t border-border pt-4"><h3 className="mb-2 font-semibold">Subject</h3><p className="text-xs capitalize text-muted-foreground">{review.subject_type} · v{review.version}</p><p className="mt-1 font-mono text-xs text-muted-foreground">{review.subject_id}</p></div><div className="border-t border-border pt-4"><h3 className="mb-2 font-semibold">Notifications</h3><Button size="sm" variant="outline" onClick={() => action.mutate(() => prReviews.subscribe(number, review.my_subscription === "muted" ? "watching" : "muted"))}>{review.my_subscription === "muted" ? "Watch review" : "Mute review"}</Button></div><div className="border-t border-border pt-4"><h3 className="mb-2 font-semibold">Approval policy</h3><p className="text-xs text-muted-foreground">{gate?.required ?? review.gate.required} required · {gate?.approvals ?? review.gate.approvals} counted</p></div></aside></div>
  </div>;
}
