# SPDX-FileCopyrightText: 2026 Rishank Jain <rishankj749@gmail.com>
# SPDX-License-Identifier: Apache-2.0
{{- if .Values.podDisruptionBudget.worker.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "observal.fullname" . }}-worker
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "observal.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  minAvailable: {{ .Values.podDisruptionBudget.worker.minAvailable }}
  selector:
    matchLabels:
      {{- include "observal.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: worker
{{- end }}
