# SPDX-FileCopyrightText: 2026 Observal contributors
# SPDX-FileCopyrightText: 2026 Srihari <sriharilegend23@gmail.com>
# SPDX-License-Identifier: Apache-2.0
"""Shared DuckDB analytics settings - imported by both client and schema modules."""

# Tables the insert endpoint accepts, and the only columns callers may write.
# The service never interpolates a caller-supplied table or column name into SQL.
ANALYTICS_TABLES: dict[str, tuple[str, ...]] = {
    "security_events": (
        "event_id",
        "timestamp",
        "event_type",
        "severity",
        "actor_id",
        "actor_email",
        "actor_role",
        "target_id",
        "target_type",
        "outcome",
        "source_ip",
        "user_agent",
        "detail",
    ),
    "audit_log": (
        "event_id",
        "timestamp",
        "actor_id",
        "actor_email",
        "actor_role",
        "action",
        "resource_type",
        "resource_id",
        "resource_name",
        "http_method",
        "http_path",
        "status_code",
        "ip_address",
        "user_agent",
        "detail",
        "sensitivity",
        "request_id",
        "outcome",
        "duration_ms",
        "chain_hash",
        "source",
    ),
    "webhook_deliveries": (
        "delivery_id",
        "event_id",
        "alert_rule_id",
        "attempt_number",
        "timestamp",
        "webhook_url",
        "status_code",
        "delivery_status",
        "error",
        "duration_ms",
        "payload_size",
    ),
    "session_events": (
        "session_id",
        "project_id",
        "user_id",
        "agent_id",
        "agent_version",
        "layer_hash",
        "harness",
        "line_offset",
        "source_end_offset",
        "line_hash",
        "source_sha256",
        "is_source_record",
        "rendered",
        "event_type",
        "timestamp",
        "uuid",
        "parent_uuid",
        "tool_name",
        "tool_id",
        "content_preview",
        "content_length",
        "raw_line",
        "ingested_at",
        "credits",
        "parent_session_id",
        "input_tokens",
        "output_tokens",
        "cache_read_tokens",
        "cache_write_tokens",
        "model",
        "raw_line_truncated",
    ),
    "session_checkpoints": (
        "session_id",
        "project_id",
        "user_id",
        "harness",
        "acknowledged_line",
        "acknowledged_offset",
        "checkpoint_version",
    ),
    "layer_snapshots": (
        "hash",
        "project_id",
        "user_id",
        "harness",
        "content",
        "file_count",
        "total_size",
        "lockfile_hash",
    ),
}

# Columns owned by the store itself (never accepted from callers).
SUMMARY_COLUMNS: tuple[str, ...] = (
    "project_id",
    "session_id",
    "agent_id",
    "agent_version",
    "user_id",
    "parent_session_id",
    "harness",
    "layer_hash",
    "first_event_time",
    "last_event_time",
    "event_count",
    "prompt_count",
    "tool_call_count",
    "tool_result_count",
    "input_tokens",
    "output_tokens",
    "cache_read_tokens",
    "cache_write_tokens",
    "total_credits",
    "model",
    "summary_version",
    "updated_at",
)

# Identity columns for append-only tables. Bulk loads delete matching rows from
# the incoming Parquet before inserting so re-running a migration cannot
# duplicate audit, security, or webhook history.
ANALYTICS_DEDUPE_KEYS: dict[str, tuple[str, ...]] = {
    "audit_log": ("event_id",),
    "security_events": ("event_id",),
    "webhook_deliveries": ("delivery_id", "attempt_number"),
}

ANALYTICS_TABLES["session_stats_agg"] = SUMMARY_COLUMNS

# Bulk migration preserves store-owned timestamp columns that callers cannot
# set through the regular insert endpoint.
ANALYTICS_LOAD_COLUMNS: dict[str, tuple[str, ...]] = dict(ANALYTICS_TABLES)
ANALYTICS_LOAD_COLUMNS["session_checkpoints"] = (*ANALYTICS_TABLES["session_checkpoints"], "updated_at")
ANALYTICS_LOAD_COLUMNS["layer_snapshots"] = (*ANALYTICS_TABLES["layer_snapshots"], "uploaded_at")

# Time column used to partition a table into monthly Parquet exports.
ANALYTICS_TIME_COLUMNS: dict[str, str] = {
    "session_events": "timestamp",
    "session_checkpoints": "updated_at",
    "session_stats_agg": "first_event_time",
    "layer_snapshots": "uploaded_at",
    "audit_log": "timestamp",
    "security_events": "timestamp",
    "webhook_deliveries": "timestamp",
}

# Target types for bulk loads from Parquet exports (DuckDB -> DuckDB).
ANALYTICS_COLUMN_TYPES: dict[str, dict[str, str]] = {
    "security_events": {
        "event_id": "VARCHAR",
        "timestamp": "TIMESTAMP",
        "event_type": "VARCHAR",
        "severity": "VARCHAR",
        "actor_id": "VARCHAR",
        "actor_email": "VARCHAR",
        "actor_role": "VARCHAR",
        "target_id": "VARCHAR",
        "target_type": "VARCHAR",
        "outcome": "VARCHAR",
        "source_ip": "VARCHAR",
        "user_agent": "VARCHAR",
        "detail": "VARCHAR",
    },
    "audit_log": {
        "event_id": "VARCHAR",
        "timestamp": "TIMESTAMP",
        "actor_id": "VARCHAR",
        "actor_email": "VARCHAR",
        "actor_role": "VARCHAR",
        "action": "VARCHAR",
        "resource_type": "VARCHAR",
        "resource_id": "VARCHAR",
        "resource_name": "VARCHAR",
        "http_method": "VARCHAR",
        "http_path": "VARCHAR",
        "status_code": "INTEGER",
        "ip_address": "VARCHAR",
        "user_agent": "VARCHAR",
        "detail": "VARCHAR",
        "sensitivity": "VARCHAR",
        "request_id": "VARCHAR",
        "outcome": "VARCHAR",
        "duration_ms": "FLOAT",
        "chain_hash": "VARCHAR",
        "source": "VARCHAR",
    },
    "webhook_deliveries": {
        "delivery_id": "VARCHAR",
        "event_id": "VARCHAR",
        "alert_rule_id": "VARCHAR",
        "attempt_number": "UTINYINT",
        "timestamp": "TIMESTAMP",
        "webhook_url": "VARCHAR",
        "status_code": "INTEGER",
        "delivery_status": "VARCHAR",
        "error": "VARCHAR",
        "duration_ms": "FLOAT",
        "payload_size": "UINTEGER",
    },
    "session_events": {
        "session_id": "VARCHAR",
        "project_id": "VARCHAR",
        "user_id": "VARCHAR",
        "agent_id": "VARCHAR",
        "agent_version": "VARCHAR",
        "layer_hash": "VARCHAR",
        "harness": "VARCHAR",
        "line_offset": "UINTEGER",
        "source_end_offset": "UBIGINT",
        "line_hash": "VARCHAR",
        "source_sha256": "VARCHAR",
        "is_source_record": "UTINYINT",
        "rendered": "UTINYINT",
        "event_type": "VARCHAR",
        "timestamp": "TIMESTAMP",
        "uuid": "VARCHAR",
        "parent_uuid": "VARCHAR",
        "tool_name": "VARCHAR",
        "tool_id": "VARCHAR",
        "content_preview": "VARCHAR",
        "content_length": "UINTEGER",
        "raw_line": "VARCHAR",
        "ingested_at": "TIMESTAMP",
        "credits": "DOUBLE",
        "parent_session_id": "VARCHAR",
        "input_tokens": "INTEGER",
        "output_tokens": "INTEGER",
        "cache_read_tokens": "INTEGER",
        "cache_write_tokens": "INTEGER",
        "model": "VARCHAR",
        "raw_line_truncated": "UTINYINT",
    },
    "session_checkpoints": {
        "session_id": "VARCHAR",
        "project_id": "VARCHAR",
        "user_id": "VARCHAR",
        "harness": "VARCHAR",
        "acknowledged_line": "BIGINT",
        "acknowledged_offset": "UBIGINT",
        "checkpoint_version": "UBIGINT",
    },
    "layer_snapshots": {
        "hash": "VARCHAR",
        "project_id": "VARCHAR",
        "user_id": "VARCHAR",
        "harness": "VARCHAR",
        "content": "VARCHAR",
        "file_count": "USMALLINT",
        "total_size": "UINTEGER",
        "lockfile_hash": "VARCHAR",
    },
    "session_stats_agg": {
        "project_id": "VARCHAR",
        "session_id": "VARCHAR",
        "agent_id": "VARCHAR",
        "agent_version": "VARCHAR",
        "user_id": "VARCHAR",
        "parent_session_id": "VARCHAR",
        "harness": "VARCHAR",
        "layer_hash": "VARCHAR",
        "first_event_time": "TIMESTAMP",
        "last_event_time": "TIMESTAMP",
        "event_count": "BIGINT",
        "prompt_count": "BIGINT",
        "tool_call_count": "BIGINT",
        "tool_result_count": "BIGINT",
        "input_tokens": "BIGINT",
        "output_tokens": "BIGINT",
        "cache_read_tokens": "BIGINT",
        "cache_write_tokens": "BIGINT",
        "total_credits": "DOUBLE",
        "model": "VARCHAR",
        "summary_version": "UBIGINT",
        "updated_at": "TIMESTAMP",
    },
}

ANALYTICS_LOAD_COLUMN_TYPES: dict[str, dict[str, str]] = {
    table: dict(types) for table, types in ANALYTICS_COLUMN_TYPES.items()
}
ANALYTICS_LOAD_COLUMN_TYPES["session_checkpoints"]["updated_at"] = "TIMESTAMP"
ANALYTICS_LOAD_COLUMN_TYPES["layer_snapshots"]["uploaded_at"] = "TIMESTAMP"
