blank_issues_enabled: true
contact_links:
  - name: Github Discussions
    url: https://github.com/BlazeUp-AI/Observal/discussions
    about: Post on the forums for questions, support and feature requests!